### PR TITLE
Convert to having a stateful client

### PR DESCRIPTION
**Pull request by jen20**
Continued from #39 (squashed commits and didn't want to force push on this repo).

This pull request introduces a large refactoring. Rather than having global state storing the subscription information, there is now a type named  azure.Client, which is initialized with an azure.Config containing the profile settings. Operations are then invoked on this client, meaning that multiple subscriptions can be managed in one process.

In addition, the package names have been rationalized, and it is necessary to pass the generic `azure.Client` to each of the specific service clients.

### CODE REVIEW

**Comment by jen20** [comment]
Heads up @phinze, this is likely to break the current azure provider in Terraform.

**Comment by anweiss** [comment]
@hopetobelievein @bfirsh Also impacts the Azure drive in Docker Machine

**Comment by jen20** [comment]
@anweiss is the docker machine stuff open source? If so I'll give you a pull request that makes the necessary changes to get this merged in.

**Comment by anweiss** [comment]
Yep. Here's the driver that uses this SDK https://github.com/docker/machine/blob/master/drivers/azure/azure.go

**Comment by ahmetalpbalkan** [comment]
It doesn't break docker-machine. They use godep. Terraform should also consider choosing something like that.

**Comment by hopetobelievein** [comment]
@anweiss Docker uses specific version of this SDK(via GoDeps), this change will not break it.

**Comment by anweiss** [comment]
Thanks @ahmetalpbalkan and @hopetobelievein ...just realized this.

**Comment by jen20** [comment]
Is there any more work required on this prior to merging?

**Comment by ahmetalpbalkan** [comment]
@jeffmendoza @hopetobelievein can you guys tag the `master` with an appropriate release number so that we can merge this PR as `2.0-rc1`?

**Comment by jeffmendoza** [comment]
Sounds good, did a v1.2 release. Merge when ready.

**Comment by ahmetalpbalkan** [comment]
Thanks for tagging @jeffmendoza 
That's awesome, thanks @jen20. Merging this breaking change `master` even though it's not thoroughly tested. Please try it out and give feedback as we go.

* @jeffmendoza you might want to start a branch off on docker-machine to try out these changes and see if it breaks anything in your flow.
* Same with you @jen20/@phinze on Terraform Azure provider.
* docker-registry uses the blob storage SDK. That hasn't changed except the import path, I'll fix it in the next godep update. cc: @stevvooe

cc: @brendandixon

**Comment by stevvooe** [comment]
@ahmetalpbalkan Could you create an issue in docker/distribution to get that updated?

**Comment by jeffmendoza** [comment]
Thanks @jen20 and @ahmetalpbalkan  !!!

**Pull request merged**
