### PR TITLE
Code tweaks:

### PR DESCRIPTION
**Pull request by jf**
- reorder BlobListResponse to be after ContainerListResponse
- standardize on "name string" parameter for the "Container" methods

Somewhat OCD, but I thought these would be good merged. Let me know what you think.

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
@jf looks good but your commit message is `Code tweaks:`.

can you please:
1. `git commit --amend --edit`
2. write a better message for the first like e.g. `refactor several methods and parameter names on blob client`
3. `git push -f your_remote codetweaks`
4. this PR will be automatically updated.

otherwise lgtm.

**Comment by jf** [comment]
Thanks, @ahmetalpbalkan . This is a multi-line commit message, actually (and the process of submitting the PR only takes the first line). You can see the complete commit message at https://github.com/jf/azure-sdk-for-go/commit/b5452045b11a43af5fa262ddd180d7cbe7592658

**Comment by ahmetalpbalkan** [comment]
I am aware but the first line should be descriptive enough. That's what appears in Commits list https://github.com/MSOpenTech/azure-sdk-for-go/commits/master

Please refer to:
* https://github.com/blog/1943-how-to-write-the-perfect-pull-request
* http://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message
* http://chris.beams.io/posts/git-commit/
* http://who-t.blogspot.com/2009/12/on-commit-messages.html

**Comment by jf** [comment]
ok, I see.

**Comment by jf** [comment]
ok I've tried to make the commit message as succinct, and yet as usefully descriptive as possible. Will this new one do?

**Comment by ahmetalpbalkan** [comment]
sounds great, though, now you need to rebase because there are merge conflicts due to latest changes :) 

1. `git fetch origin` (i.e. origin = this msopentech remote)
2. `git rebase origin/master`
3. `git push -f your_remote codetweaks`

**Comment by jf** [comment]
Got it. The new code is in and rebased.

**Comment by ahmetalpbalkan** [comment]
Thanks @jf. Feel free to "watch" the repo to get notified about other changes.

**Pull request merged**
